=== oct15demo/browserUI/org.knime.core/src/eclipse/org/knime/core/node/Node.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
===============================================================================
 *  Copyright by KNIME GmbH, Konstanz, Germany
 *  Website: http://www.knime.com; Email: contact@knime.com
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License, Version 3, as
 *  published by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 *  Additional permission under GNU GPL version 3 section 7:
 *
 *  KNIME interoperates with ECLIPSE solely via ECLIPSE's plug-in APIs.
 *  Hence, KNIME and ECLIPSE are both independent programs and are not
 *  derived from each other. Should, however, the interpretation of the
 *  GNU GPL Version 3 ("License") under any applicable laws result in
 *  KNIME and ECLIPSE being a combined program, KNIME GMBH herewith grants
 *  you the additional permission to use and propagate KNIME together with
 *  ECLIPSE with only the license terms in place for ECLIPSE applying to
 *  ECLIPSE and the GNU GPL Version 3 applying for KNIME, provided the
 *  license terms of ECLIPSE themselves allow for the respective use and
 *  propagation of ECLIPSE together with KNIME.
 *
 *  Additional permission relating to nodes for KNIME that extend the Node
 *  Extension (and in particular that are based on subclasses of NodeModel,
 *  NodeDialog, and NodeView) and that only interoperate with KNIME through
 *  standard APIs ("Nodes"):
 *  Nodes are deemed to be separate and independent programs and to not be
 *  covered works.  Notwithstanding anything to the contrary in the
 *  License, the License does not apply to Nodes, you are not required to
 *  license Nodes under the License, and you are granted a license to
 *  prepare and propagate Nodes, in each case even if such Nodes are
 *  propagated with or for interoperation with KNIME.  The owner of a Node
 *  may freely choose the license terms applicable to such Node, including
 *  when such Node is propagated with or for interoperation with KNIME.
===============================================================================
-->
<!ELEMENT knimeNode ( name, shortDescription, fullDescription, ports, views? ) >
<!ATTLIST knimeNode icon CDATA #IMPLIED>
<!ATTLIST knimeNode type (Source|Sink|Learner|Predictor|Manipulator|Visualizer|Meta|LoopStart|LoopEnd|ScopeStart|ScopeEnd|QuickForm|Other|Unknown) "Unknown">
<!ATTLIST knimeNode deprecated (true|false) "false">

<!ELEMENT name (#PCDATA) >
<!ELEMENT shortDescription (#PCDATA) >

<!ELEMENT fullDescription (intro, (option*|tab*)) >
<!ELEMENT intro (#PCDATA | p | h | br | b | i | u | tt | a | ul | ol | h3 | h4 | pre | sub | sup | table)* >
<!ELEMENT option (#PCDATA | p | h | br | b | i | u | tt | a | ul | ol | pre | sub | sup)* >
<!ATTLIST option name CDATA #REQUIRED>
<!ATTLIST option optional (true|false) "false">
<!ELEMENT tab (option+)>
<!ATTLIST tab name CDATA #REQUIRED>

<!ELEMENT p (#PCDATA | br | b | i | u | a | tt | ul | ol | sup | sub)* >
<!ELEMENT ul (li)+ >
<!ELEMENT ol (li)+ >
<!ELEMENT li (#PCDATA | br | b | i | u | a | tt)* >
<!ELEMENT h3 (#PCDATA) >
<!ELEMENT h4 (#PCDATA) >
<!ELEMENT h (#PCDATA) >
<!ELEMENT b (#PCDATA) >
<!ELEMENT i (#PCDATA) >
<!ELEMENT u (#PCDATA) >
<!ELEMENT a (#PCDATA) >
<!ELEMENT tt (#PCDATA) >
<!ELEMENT pre (#PCDATA) >
<!ELEMENT sup (#PCDATA) >
<!ELEMENT sub (#PCDATA) >
<!ELEMENT br EMPTY >
<!ATTLIST a href CDATA #REQUIRED>

<!ELEMENT table (tr)+ >
<!ELEMENT tr (th | td)+ >
<!ELEMENT td (#PCDATA) >
<!ELEMENT th (#PCDATA) >
<!ATTLIST td align CDATA #IMPLIED>
<!ATTLIST th align CDATA #IMPLIED>
<!ATTLIST td colspan CDATA #IMPLIED>
<!ATTLIST th colspan CDATA #IMPLIED>
<!ATTLIST td rowspan CDATA #IMPLIED>
<!ATTLIST th rowspan CDATA #IMPLIED>


<!ELEMENT ports (inPort*, outPort*) >
<!ELEMENT inPort (#PCDATA | br | b | i | u | tt | ul | ol)* >
<!ATTLIST inPort index CDATA #REQUIRED>
<!ATTLIST inPort name CDATA #REQUIRED>
<!ATTLIST inPort optional (true|false) "false">
<!ELEMENT outPort (#PCDATA | br | b | i | u | tt | ul | ol)* >
<!ATTLIST outPort index CDATA #REQUIRED>
<!ATTLIST outPort name CDATA #REQUIRED>

<!ELEMENT views (view+) >
<!ELEMENT view (#PCDATA | p | h | br | b| i | u | tt | a | ul | ol | pre | sub | sup)* >
<!ATTLIST view index CDATA #REQUIRED>
<!ATTLIST view name CDATA #REQUIRED>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/preproc/binner/BinnerNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="./binner.png" type="Manipulator">
	<name>Numeric Binner</name>
	
	<shortDescription>
	    Group values of numeric columns categorized string type.
	</shortDescription>
	
	<fullDescription>
		<intro>		
	    For each column a number of intervals - known as bins - can be defined. 
	    Each of these bins is given a unique name (for this column), a defined 
	    range, and open or closed interval borders. They automatically ensure 
	    that the ranges are defined in descending order and that interval 
	    borders are consistent. In addition, each column is either replaced with
	    the binned, string-type column, or a new binned, string-type column 
	    is appended.
		</intro>
		
		<option name="Select Column: ">
		First select a column (left side) and then use the "Add" button (right 
		side) to create the desired number of bins. Each bin can be modified in 
		the lower part of this panel once it has been selected.
        Each interval has to be defined independently or can be removed using
        the "Remove" button. Note that the range as well as the bin borders can
        be automatically adjusted, if necessary.
        The first bin's left and the last bin's right value are 
        automatically defined to infinitely cover the entire numeric axes in 
        this direction. Furthermore, each bin's left and right value can be 
        included or excluded from this bin by selecting the desired bracket:
        '[' or ']'.
        
		</option>
		<option name="Append new column: ">
		If selected, a new column name can be specified. This name is given to 
		the new binned column that is appended to the table; the input column 
		remains unchanged in the data.
		</option>
	</fullDescription>
	
	<ports>
		<inPort index="0" name="Input Data">Data to define bins</inPort>
		<outPort index="0" name="Binned Data">Data with bins defined</outPort>
	</ports>	
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/util/extracttabledimension/ExtractTableDimensionNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="extracttabledimension.png" type="Other">
    <name>Extract Table Dimension</name>
    <shortDescription>Extracts the number of rows and columns of the input table
        and outputs them as data table and flow variables.  
    </shortDescription>
    <fullDescription>
        <intro>
			The number of rows and columns of the input table are 
			extracted and written to the output table. The output table consists
			of two rows and one column. The first row contains the number of
			rows and the second row contains the number of columns of the input
			table. Additionally the two numbers are pushed out as flow 
			variables.		
		</intro>
	</fullDescription>
		
	<ports>
        <inPort name="Input table with dimensions to extract" index="0">
            The input table for which dimensions are extracted.
        </inPort>
        <outPort name="Table containing dimensions" index="0">
        	The output table containing the dimensions of the input table.
        </outPort>
	</ports>
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/viz/enrichment2/EnrichmentPlotterFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="./enrichment.png" type="Visualizer">
	<name>Enrichment Plotter</name>
	<shortDescription>
		Draws enrichment curves
	</shortDescription>
	<fullDescription>
		<intro>
			This node draws enrichment curves often used in virtual screening.
			For this the user can choose a column by which the data is sorted and
			represents the x-axis. The values on the y-axis are formed by the sum
			of the hits in a second column that is also selected by the user. A
			row is considered a hit if the activity value is greater than 0. The
			steeper the resulting curve, the better the enrichment is. Optionally
			the y-axis can show the sum of the activity values instead of the
			number of hits.
			<br />
			The two gray lines in the view show the enrichment if the data points
			were ordered randomly (lower diagonal) and the optimal enrichment if
			all hits are ordered before the first non-hit (upper diagonal).
		</intro>

		<option name="Plot sum of hit values">
			Check this if the y-axis should show the sum of
			the values in the activity column.
		</option>
		<option name="Plot hits">
			Check this and enter a threshold if the y-axis
			should show the sum of data points that have values equal to or
			greater
			than the threshold.
		</option>
		<option name="Plot discovered clusters">
			Check this if the y-axis should show the number of
			discovered clusters. A cluster is considered to be found once the set
			number of molecules in this cluster has been found.
		</option>
		<option name="Fraction sizes (in %)">
			Size of the fractions to calculate the discovery
			rates and enrichment factors of.
		</option>
		<option name="Sort column">
			Select the column by which the rows should be
			sorted and plotted as the x-axis.
		</option>
		<option name="Activity column">
			Select the column that contains the activity
			values.
		</option>
		<option name="Sort descending">
			Checking this before adding a curve sorts the data
			points in the sort column descendingly instead of ascendingly. This
			is a setting specific to each curve.
		</option>
	</fullDescription>
	<ports>
		<inPort index="0" name="Input table">
			Input data with values to sort by and
			actual activity values
		</inPort>
		<outPort index="0" name="Areas under curve">
			A one-column table with the area(s)
			under the enrichment curve(s)
		</outPort>
		<outPort index="1" name="Discovery rates + enrichment factors">
			Table with the discovery rates (either
			hits or clusters) for the different curves at the selected faction
			sizes. Also contains the enrichment factors which describe how many
			times better the given order is compared to a random order.
		</outPort>
	</ports>
	<views>
		<view index="0" name="Enrichment Plot">
			Enrichment plot
		</view>
	</views>
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/mine/pca/PCAComputeNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="./pca_compute.png" type="Manipulator">
	<name>PCA Compute</name>
	<shortDescription>Principal component analysis computation</shortDescription>
	<fullDescription>
		<intro>
			This node performs a
			<a href="http://en.wikipedia.org/wiki/Principal_component_analysis">
				principal component analysis (PCA)</a>
			on the given input data.
			The directions of maximal variance (the principal components) are
			extracted and can be used in the PCA Apply node
			to project the input into a space of lower dimension while preserving a
			maximum of information.
		</intro>
		<option name="Fail if missing values are encountered">
			If checked, execution fails, when the selected columns contain missing
			values.
			By default, rows containing missing values are ignored and not
			considered in the computation of the principal components.
		</option>
		<option name="Columns">
			Select the columns that are included in the analysis of principal
			components, i.e. the numerical features of the data.
		</option>
	</fullDescription>
	<ports>
		<inPort index="0" name="Table to transform">Input data for the PCA</inPort>
		<outPort index="0" name="Covariance matrix">Covariance matrix of the input columns</outPort>
		<outPort index="1" name="Spectral decomposition">
			Table containing parameters extracted from the PCA. Each row in the
			table represents one principal component, whereby the rows are sorted
			with decreasing eigenvalues, i.e. variance along the corresponding
			principal axis. The first column in the table contains the component's
			eigenvalue, a high value indicates a high variance (or in other words,
			the respective component dominates the orientation of the input data).
			<br />
		    Each subsequent column (labeled with the name of the selected 
		    input column) contains a coefficient representing the influence
		    of the respective input dimension to the principal component. 
		    The higher the absolute value, the higher the influence of the
		    input dimension on the principal component. 
			<br />
		    The mapping of the input rows to, e.g. the first principal axis, 
		    is computed as follows (all done in the PCA Apply node): 
		    For each dimension in the original space subtract the dimension's
		    mean value and then multiply the resulting vector with the vector 
		    given by this table (the first row in the spectral decomposition 
		    table to get the value on the first PC, the second row for the 
		    second PC and so on).    
		</outPort>
		<outPort index="2" name="Projection model">Model with projection to principal
			components, used in the PCA Apply node to apply the transformation
			to, e.g. another validation set.
	    </outPort>

	</ports>
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/viz/plotter/parcoord/ParallelCoordinateNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="./parallelCoordinates.png" type="Visualizer">
	<name>Parallel Coordinates</name>
	
	<shortDescription>
	   Plots the data in Parallel Coordinates.
	</shortDescription>
	
	<fullDescription>
		<intro>
		<p>During the 1980’s and early 90’s, Inselberg and
		Dimsdale (A. Inselberg and B. Dimsdale, "Parallel Coordinates: A Tool
		for Visualizing Multidimensional Geometry," Proc. IEEE
		Figure 11. Before and after a focus and
		context effect is introduced.
		Visualization 1990, IEEE Computer Society Press, San
		Francisco, California, USA, October 23-25, 1990, pp. 361-378.) 
		introduced Parallel Coordinates, a
		representation of multi-dimensional information or data, in
		which multiple dimensions are allocated one-to-one to an
		equal number of parallel axes on-screen. An object in a
		data set is then mapped as a series of points, one per axis,
		with the position of each point on the axis being
		dependent on their value in the associated dimension. The
		points are then joined together by line segments from one
		axis to its immediate neighbour, forming a poly-line across
		the set of axes.
		</p>
		
       <p><b>Only columns with a valid domain are available in this view.
        Make sure that the predecessor node is executed or set the domain 
        with the DomainCalculator node!</b></p>		
		
		<h3>HiLiting:</h3>
		<p> The data points may be selected by either dragging
		a rectangle with the mouse over the points on the parallel axes or 
		by clicking on points or connecting line segments 
		(if curves are drawn, selection works only on the datapoints). Hold 
		control pressed for multiple selections. 
		The selected datapoints may be 
		hilited by either right-click to get the context menu or via the hilite
		menu in the menu bar.</p>
		
		<h3>Tooltip</h3>
		<p>
		Move the mouse over the data points on the parallel axis to get 
		information about the row ID and the value.
		</p>
		
		<h3>Properties: </h3>
		<p>Default Settings:
			<ul>
			<li>Mouse Mode: choose "Selection" to select the datapoints or
			"Zooming" to zoom in. If you have zoomed in you may choose "Moving" 
			to navigate in the zoomed display. If you want to rearrange the parallel
			axes choose "Transformation". The axes can then be selected and dragged
			to another position.</li>
			<li>"Fit to screen" fits the display again to the available space.</li>
			<li>"Background color lets you choose the background color of the display. </li>
            <li>"Anti-aliasing": Check if the view should enable anti-aliasing
            (make a smoother drawing). This will slow down performance as well.</li>
			</ul>
		</p>
		<p>Column Selection:
		Choose the columns you want to have displayed as parallel axes.
		</p>
		<p>Missing Values:
			<ul>
			<li>"Skip rows containing missing values": if a row contains a missing 
			value, this row is not displayed (Default)</li>
			<li>"Skip only the missing value" would interrupt the line by leaving
			out the missing value at the referring parallel axis.</li>
			<li>"Show missing values" draws a horizontal bar at the bottom and maps
			the missing values to this bar. This provides a quick overview over 
			the existence and distribution of missing values.</li>
			</ul>
		</p>
		<p>Appearance:
			<ul>
			<li>"Show/Hide dots": Check if the points on the parallel axes should
			be displayed explicitly as dots; uncheck if you want to hide the dots.</li>
			<li>"Draw curves instead of lines": Connects the datapoints not with linear
			interpolated line segments but with cubic curves. In this way it is easier
			to see one sample (row) since the continuation of the line after a common 
			data point can easily be seen (see: m. Graham, J.Kennedy: "Using Curves to Enhance Parallel 
			Coordinate Visualizations").</li>
			</ul>
		</p>

		</intro>
		<option name="Nr. of rows to display">Enter the maximum number of rows
		the plotter should display. Setting a higher value than the default value 
		might dramatically decrease performance.</option>
		<option name="Ignore columns with more nominal values than:">
            Enter the maximum number of distinct nominal values that the
            view should consider. Columns with more values than the
            specified number will be ignored and can't be selected in
            the view. Please also note that nominal values must be
            present in the table specification of the input table (check
            it by inspecting the table spec tab of the predecessor's
            outport view). If no nominal values are present in the
            table, execute the predecessor or consider to use the 
            "Domain Calculator" node and to enforce the determination of 
            the nominal values.
        </option>
	</fullDescription>
	
	<ports>
		<inPort index="0" name="Display data">Data to display</inPort>
	</ports>	
	<views>
		<view index="0" name="Parallel Coordinates">
			Parallel Coordinates displaying the data as points on parallel axes 
			connected with interpolated line segments.
		</view>
	</views>
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/preproc/colconvert/categorytonumber2/CategoryToNumberNodeFactory2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="./categoryToNumber.png" type="Manipulator">
	<name>Category To Number</name>
	
	<shortDescription>
		Maps each category of a column with nominal data to an integer.
	</shortDescription>
	
	<fullDescription>
		<intro>
		This node takes columns with nominal data and maps every category to
		an integer. For your convenience, you can process multiple columns with this
		node. However, these columns are processed separately as if you would
	    use a single Cateory To Number node for every column.
		</intro>
			<option name="Columns">
				Include the columns that should be processed. You can only
				include columns with nominal data. 
			</option>
            <option name="Append columns">
                If checked, the computed columns will be appended to the 
                input table. Otherwise the computed columns replace the 
                columns in the include list. 
            </option>
            <option name="Column suffix">
                The column name of the computed columns are the name of the 
                column in the input appended by this suffix.
            </option>
            <option name="Start value">
                The category in the first row will be mapped to this value.
            </option>
            <option name="Increment">
                The i-th category is mapped to the value i * Increment + Start value.
            </option>
            <option name="Max. categories">
                Processing is interrupted for inputs with more than categories
                than max. categories. 
            </option>
            <option name="Default value">
                This value is used when the PMML model is applied. It defines 
                the value used when the input is not found in the mapping.
                Leave it empty to assign a missing cell in this case.
            </option>
            <option name="Map missing to">
                Missing cells are mapped to this value. You can enter any
                integer. If empty, missing cells will be mapped to missing cells.
            </option>
            </fullDescription>
	
	<ports>
		<inPort index="0" name="Data to process">Data</inPort>
		<inPort index="1" name="PMML Document">Optional PMML document to add the map values operations to.</inPort>
		<outPort index="0" name="Processed data">Data with transformed columns</outPort>
        <outPort index="1" name="Transformed PMML input">PMML port object that includes the performed operations.</outPort>
	</ports>	
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/viz/property/color/ColorAppender2NodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode type="Visualizer" icon="./color_appender.png">
	<name>Color Appender</name>
	
	<shortDescription>
	    Assigns an existing color model to a table. 
	</shortDescription>
	
	<fullDescription>
		<intro>
		<p>
		Assigns an existing color model to a table. 		
		If a color model was configured
	    for a dataset and this color model should be reused, the model outport 
	    of the Color Manager should be connected to the model inport of the Color Appender.
	    In the Color Appender the color model could also be applied to another column.
	    This works for numeric columns unrestricted and for nominal columns only if 
	    the possible values are exactly the same. In general a color model for nominal values
	    is incompatible with a color model for numeric values.
	    </p>
	    
	    <p>
	    This may be useful if the column for which the color model is defined gets
	    lost somewhere in the workflow or is replaced by another column or if there
	    are two different datasets with the same class column. 
	    </p>
		</intro>
	    <option name="Append colors to: ">
		    Select the column to apply color settings to. It might be the same column, 
		    a different numeric column for which the color settings should be reused, 
		    or a nominal column if the color model was defined for nominal values. 
		    Then the possible values must be exactly the same. Color models
		    for numeric and for nominal values are not compatible with each other.
	    </option>
	</fullDescription>
	
	<ports>
		<inPort index="0" name="Color Settings">Existing color model to be applied to the input table</inPort>
		<inPort index="1" name="Table">Table to which colors are applied to</inPort>
		<outPort index="0" name="Table with Colors">Table with colors for the selected column</outPort>
	</ports>	
	
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/preproc/filter/hilite/HiliteFilterNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="./hiliterowfilter.png" type="Manipulator">
    <name>HiLite Row Splitter</name>
    <shortDescription>Partitions input rows based on their current hilite status.</shortDescription>
    <fullDescription>
        <intro>
			This node separates hilited from non-hilited rows in the
			input data according to their hilite status at the time of 
			node's execution. Both tables are then passed to out-ports. Note, 
			hilite changes that happen after the execution are not reflected 
			in the output tables. You will need to reset and execute the node
			again if you want to get a partitioning based on the changed state.
		</intro>	
	</fullDescription>
		
	<ports>
        <inPort name="Input data" index="0">Input data.</inPort>
        <outPort name="Output data containing hilited rows" index="0">
        The filtered output table containing hilited rows only.</outPort>
        <outPort name="Output data containing non-hilited rows" index="1">
        The filtered output table containing non-hilited rows only.</outPort>
	</ports>
</knimeNode>
