=== oct15demo/browserUI/org.knime.core/src/eclipse/org/knime/core/node/Node.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
===============================================================================
 *  Copyright by KNIME GmbH, Konstanz, Germany
 *  Website: http://www.knime.com; Email: contact@knime.com
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License, Version 3, as
 *  published by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 *  Additional permission under GNU GPL version 3 section 7:
 *
 *  KNIME interoperates with ECLIPSE solely via ECLIPSE's plug-in APIs.
 *  Hence, KNIME and ECLIPSE are both independent programs and are not
 *  derived from each other. Should, however, the interpretation of the
 *  GNU GPL Version 3 ("License") under any applicable laws result in
 *  KNIME and ECLIPSE being a combined program, KNIME GMBH herewith grants
 *  you the additional permission to use and propagate KNIME together with
 *  ECLIPSE with only the license terms in place for ECLIPSE applying to
 *  ECLIPSE and the GNU GPL Version 3 applying for KNIME, provided the
 *  license terms of ECLIPSE themselves allow for the respective use and
 *  propagation of ECLIPSE together with KNIME.
 *
 *  Additional permission relating to nodes for KNIME that extend the Node
 *  Extension (and in particular that are based on subclasses of NodeModel,
 *  NodeDialog, and NodeView) and that only interoperate with KNIME through
 *  standard APIs ("Nodes"):
 *  Nodes are deemed to be separate and independent programs and to not be
 *  covered works.  Notwithstanding anything to the contrary in the
 *  License, the License does not apply to Nodes, you are not required to
 *  license Nodes under the License, and you are granted a license to
 *  prepare and propagate Nodes, in each case even if such Nodes are
 *  propagated with or for interoperation with KNIME.  The owner of a Node
 *  may freely choose the license terms applicable to such Node, including
 *  when such Node is propagated with or for interoperation with KNIME.
===============================================================================
-->
<!ELEMENT knimeNode ( name, shortDescription, fullDescription, ports, views? ) >
<!ATTLIST knimeNode icon CDATA #IMPLIED>
<!ATTLIST knimeNode type (Source|Sink|Learner|Predictor|Manipulator|Visualizer|Meta|LoopStart|LoopEnd|ScopeStart|ScopeEnd|QuickForm|Other|Unknown) "Unknown">
<!ATTLIST knimeNode deprecated (true|false) "false">

<!ELEMENT name (#PCDATA) >
<!ELEMENT shortDescription (#PCDATA) >

<!ELEMENT fullDescription (intro, (option*|tab*)) >
<!ELEMENT intro (#PCDATA | p | h | br | b | i | u | tt | a | ul | ol | h3 | h4 | pre | sub | sup | table)* >
<!ELEMENT option (#PCDATA | p | h | br | b | i | u | tt | a | ul | ol | pre | sub | sup)* >
<!ATTLIST option name CDATA #REQUIRED>
<!ATTLIST option optional (true|false) "false">
<!ELEMENT tab (option+)>
<!ATTLIST tab name CDATA #REQUIRED>

<!ELEMENT p (#PCDATA | br | b | i | u | a | tt | ul | ol | sup | sub)* >
<!ELEMENT ul (li)+ >
<!ELEMENT ol (li)+ >
<!ELEMENT li (#PCDATA | br | b | i | u | a | tt)* >
<!ELEMENT h3 (#PCDATA) >
<!ELEMENT h4 (#PCDATA) >
<!ELEMENT h (#PCDATA) >
<!ELEMENT b (#PCDATA) >
<!ELEMENT i (#PCDATA) >
<!ELEMENT u (#PCDATA) >
<!ELEMENT a (#PCDATA) >
<!ELEMENT tt (#PCDATA) >
<!ELEMENT pre (#PCDATA) >
<!ELEMENT sup (#PCDATA) >
<!ELEMENT sub (#PCDATA) >
<!ELEMENT br EMPTY >
<!ATTLIST a href CDATA #REQUIRED>

<!ELEMENT table (tr)+ >
<!ELEMENT tr (th | td)+ >
<!ELEMENT td (#PCDATA) >
<!ELEMENT th (#PCDATA) >
<!ATTLIST td align CDATA #IMPLIED>
<!ATTLIST th align CDATA #IMPLIED>
<!ATTLIST td colspan CDATA #IMPLIED>
<!ATTLIST th colspan CDATA #IMPLIED>
<!ATTLIST td rowspan CDATA #IMPLIED>
<!ATTLIST th rowspan CDATA #IMPLIED>


<!ELEMENT ports (inPort*, outPort*) >
<!ELEMENT inPort (#PCDATA | br | b | i | u | tt | ul | ol)* >
<!ATTLIST inPort index CDATA #REQUIRED>
<!ATTLIST inPort name CDATA #REQUIRED>
<!ATTLIST inPort optional (true|false) "false">
<!ELEMENT outPort (#PCDATA | br | b | i | u | tt | ul | ol)* >
<!ATTLIST outPort index CDATA #REQUIRED>
<!ATTLIST outPort name CDATA #REQUIRED>

<!ELEMENT views (view+) >
<!ELEMENT view (#PCDATA | p | h | br | b| i | u | tt | a | ul | ol | pre | sub | sup)* >
<!ATTLIST view index CDATA #REQUIRED>
<!ATTLIST view name CDATA #REQUIRED>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/preproc/caseconvert/CaseConvertNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="./case_converter.png" type="Manipulator">
	<name>Case Converter</name>
	
	<shortDescription>
	    This node converts alphanumeric characters to lowercase or UPPERCASE.
	</shortDescription>
	
	<fullDescription>
		<intro>
			This node converts alphanumeric characters to lowercase or UPPERCASE.
		</intro>
		<option name="Select Mode">
		<p>
		<b>Convert to UPPERCASE</b> : Selected string columns are transformed to uppercase. 
		</p>
		<p>
		<b>Convert to lowercase</b>: Selected string columns are transformed to lowercase.</p></option>	
		<option name="Column Selection">Move the columns of interest into the &quot;Include&quot; list</option>
	</fullDescription>
	
	<ports>
		<inPort index="0" name="Input">Arbitrary input data.</inPort>
		<outPort index="0" name="Transformed input">Input data with transformed string values.</outPort>
	</ports>	
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/preproc/colconvert/stringtonumber/StringToNumberNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="./string_number.png" type="Manipulator">
	<name>String To Number</name>
	
	<shortDescription>
	    Converts strings in a column to numbers.
	</shortDescription>
	
	<fullDescription>
		<intro>
			Converts strings in a column (or a set of columns) to numbers.
			If the node fails to parse a string, it will generate a missing cell and append
	    	a warning message to the KNIME Console with detailed information.
		</intro>
		  <option name="Type">Choose the DataType that your string should
		  be converted to.</option>
    	<option name="Decimal Separator">Choose a decimal separator, 
		which is used to mark the boundary between the integral and the 
		fractional parts of the decimal string.</option>
		<option name="Thousands Separator">Choose a thousands separator 
		used in the decimal string to group together three digits.</option>
		<option name="Accept type suffix, e.g. 'd', 'D', 'f', 'F'">When checked, the type suffix will be
		accepted, otherwise it fails to parse input like <tt>1d</tt>. These suffixes are typically used
        in java-style programs to represent floating point numbers ('f' for float and 'd' for double). Default is 
        not checked. </option>
		<option name="Column Selection">
		Move the columns of interest into the
		&quot;Include&quot; list</option>
		
		
	</fullDescription>
	
	<ports>
		<inPort index="0" name="Input">Arbitrary input data.</inPort>
		<outPort index="0" name="Transformed input">Input data with new DoubleTypes.</outPort>
	</ports>	
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/mine/decisiontree2/image/DecTreeToImageNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="./dectree_image.png" type="Manipulator">
    <name>Decision Tree To Image</name>
    
    <shortDescription>
        Renders a decision tree view on an image (PNG).
    </shortDescription>
    
    <fullDescription>
        <intro>        
        Renders a decision tree view on an image. Currently supported image
        type is PNG. The data input is optional. It can be used to provide a
        column with color information. This color information is needed for 
        the chart in the nodes of the decision tree.
        </intro>
        
        <option name="Width (in Pixel)">
            The width of the image.
        </option>        
        <option name="Collapse Table">
            The height of the image.
        </option>
        <option name="Tree Scaling">
            To make sure that the decision tree is completely rendered on the
            image you would choose <b>Shrink to image area</b>. With 
            <b>Fit to image area</b> the tree may also be scaled up to fit the
            image area. Finally, <b>Fixed value</b> gives control over the
            scaling magnitude.            
        </option>
        <option name="Zoom">
            The scaling magnitude for the tree scaling option <b>Fixed value</b>. 
        </option>
        <option name="Branch Display">
            With this options you can restrict the number of branches (nodes) 
            of the tree rendered on the image. Using 
            <b>Unfold with data coverage</b>, all branches will be unfolded that
            have a total data coverage greater than the given value. With
            <b>Unfold to level</b>, the tree will be unfolded to the given
            level where the root is on level 0 and its children on level 1.
        </option>
        <option name="Node Display">
            Controls the style how the nodes of the tree are displayed. You 
            can choose to hide the table ore the chart in the nodes. Note, that
            the chart will show up only when the data input provides a column
            with color information. 
        </option>
    </fullDescription>
    
    <ports>
        <inPort index="0" name="Decision Tree Model">A previously learned decision tree model</inPort>
        <inPort index="1" name="Data (color information)">A data input which has the only purpose to provide a columns with color information.</inPort>
        <outPort index="0" name="Image">The image of the decision tree (PNG)</outPort>
    </ports>

    
    <views>
        <view index="0" name="Decision Tree View">
            The rendered image. The second tab provides a dynamic decision
            tree view which allows to explore the decision tree.
        </view>
    </views>
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/preproc/normalize/NormalizerApplyNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="./normalizeapply.png" type="Manipulator">
    <name>Normalizer (Apply)</name>
    <shortDescription>Normalizes the attributes of a table according to a model.</shortDescription>
    <fullDescription>
        <intro>
	        <p>
        	This node normalizes the input data according to the normalization parameters
        	as given in the model input (typically coming from the Normalizer node). It
        	will apply an affine transformation to all columns in the input data that
        	are contained in the model input.
        	</p>
        	<p>
        	This node is typically used when test data shall be normalized the same
        	way the training data has been normalized (using the "Normalizer" node).
        	</p>
		</intro>
	</fullDescription>
    <ports>
        <inPort index="0" name="Model">Normalization parameters</inPort>
        <inPort index="1" name="Table to normalize">Table requiring normalization of some or all columns.</inPort>
        <outPort index="0" name="Normalized output">The input data normalized according to the normalization parameters.</outPort>
	</ports>
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src-deprecated/org/knime/base/node/mine/svm/predictor/SVMPredictorNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="./SVM_predict.png" type="Predictor" deprecated="true">
	<name>SVM Predictor</name>
	<shortDescription>
	    This node uses a SVM model generated by the SVM learner
		node to predict the output for given parameters.
	</shortDescription>
	
	<fullDescription>
	<intro>
		This node uses a SVM model generated by the SVM learner
		node to predict the output for given values. Only the columns
		that have been used during training are used in
		the SVM learner. The output table will contain one extra
		column, which contains the prediction. There is no need
		to configure this node.
		</intro>
	</fullDescription>
	
	<ports>
		<inPort index="0" name = "Trained SVM">The model generated by the SVM Learner</inPort>
		<inPort index="1" name = "Test Data">Inport for the input table</inPort>
		<outPort index="0" name = "Classification">The input table, with the prediction column appended to it.</outPort>
	</ports>	
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/preproc/transpose/TransposeTableNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode type="Manipulator" icon="./transpose.png">
    <name>Transpose</name>
    <shortDescription>Transposes a table by swapping rows and columns.</shortDescription>
    <fullDescription>
        <intro>
			Transposes the entire input table by swapping rows and columns. The new column
		    names are provided by the former (old) row IDs and the new row identifiers are 
		    the former (old) column names. The new column type is the most specific
		    base type and applies to all cells in one row.
		</intro>
		<option name=" Chunk size (columns):">
		      number of columns read during one iteration over the table, increasing this
		      value yields faster execution time but also increases memory consumption.
		</option>
	</fullDescription>
    <ports>
        <inPort index="0" name="Table">Input data to transpose</inPort>
        <outPort index="0" name="Transposed Table">Table transposed by swapping rows and columns</outPort>
	</ports>
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/flowvariable/variableloophead/LoopStartVariableNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="tablerow2variable_loop.png" type="LoopStart">
    <name>Table Row To Variable Loop Start</name>
    
    <shortDescription>
        Iterates over an input data table, whereby each row defines on iteration
        with variable settings taken from the values in that row  
    </shortDescription>
    
    <fullDescription>
        <intro>
          This node uses each row of a data table to define new
          variable values for each loop iteration. The names of the variables
          are defined by the column names.
        </intro>
        <option name="Fail">If selected the node fails with an error on Missing Values or empty tables.</option>
		<option name="Defaults">If selected the node replaces Missing Values or empty table columns by either integer, double, or String values as defined.</option>
		<option name="Omit">If selected the node ignores Missing Values or empty table columns.</option>
    </fullDescription>
    
    <ports>
        <inPort index="0" name="Parameters table">The table whose 
          rows will constitute variables' values for each iteration.</inPort>
        <outPort index="0" name="Variable connection">
            The connection passing on the variable values to the next
            nodes.</outPort>
    </ports>
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/io/database/DBConnectionNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode type="Source" icon="./db_connection_reader.png">
	<name>Database Connection Table Reader</name>
	
	<shortDescription>
	    Reads the entire data from the input database connection.
	</shortDescription>
	
	<fullDescription>
		<intro>		
	     Opens a database connection based on the input settings and reads
	     the entire data table from the database into KNIME. 
		</intro>
		<option name="Use database row id">If enabled the KNIME row id is based on the row id returned from the database.
		An internal counter is used to generate the row id if the option is disabled.
		<b>If you encounter a duplicate key exception disable this option.</b> This is caused by a faulty implementation 
		of the used jdbc driver.</option>
	</fullDescription>
	
	<ports>
		<inPort index="0" name="Database Connection">Database connection to a table</inPort>
		<outPort index="0" name="Data read from Database">Database read from database</outPort>
	</ports>	
</knimeNode>
