=== oct15demo/browserUI/org.knime.core/src/eclipse/org/knime/core/node/Node.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
===============================================================================
 *  Copyright by KNIME GmbH, Konstanz, Germany
 *  Website: http://www.knime.com; Email: contact@knime.com
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License, Version 3, as
 *  published by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 *  Additional permission under GNU GPL version 3 section 7:
 *
 *  KNIME interoperates with ECLIPSE solely via ECLIPSE's plug-in APIs.
 *  Hence, KNIME and ECLIPSE are both independent programs and are not
 *  derived from each other. Should, however, the interpretation of the
 *  GNU GPL Version 3 ("License") under any applicable laws result in
 *  KNIME and ECLIPSE being a combined program, KNIME GMBH herewith grants
 *  you the additional permission to use and propagate KNIME together with
 *  ECLIPSE with only the license terms in place for ECLIPSE applying to
 *  ECLIPSE and the GNU GPL Version 3 applying for KNIME, provided the
 *  license terms of ECLIPSE themselves allow for the respective use and
 *  propagation of ECLIPSE together with KNIME.
 *
 *  Additional permission relating to nodes for KNIME that extend the Node
 *  Extension (and in particular that are based on subclasses of NodeModel,
 *  NodeDialog, and NodeView) and that only interoperate with KNIME through
 *  standard APIs ("Nodes"):
 *  Nodes are deemed to be separate and independent programs and to not be
 *  covered works.  Notwithstanding anything to the contrary in the
 *  License, the License does not apply to Nodes, you are not required to
 *  license Nodes under the License, and you are granted a license to
 *  prepare and propagate Nodes, in each case even if such Nodes are
 *  propagated with or for interoperation with KNIME.  The owner of a Node
 *  may freely choose the license terms applicable to such Node, including
 *  when such Node is propagated with or for interoperation with KNIME.
===============================================================================
-->
<!ELEMENT knimeNode ( name, shortDescription, fullDescription, ports, views? ) >
<!ATTLIST knimeNode icon CDATA #IMPLIED>
<!ATTLIST knimeNode type (Source|Sink|Learner|Predictor|Manipulator|Visualizer|Meta|LoopStart|LoopEnd|ScopeStart|ScopeEnd|QuickForm|Other|Unknown) "Unknown">
<!ATTLIST knimeNode deprecated (true|false) "false">

<!ELEMENT name (#PCDATA) >
<!ELEMENT shortDescription (#PCDATA) >

<!ELEMENT fullDescription (intro, (option*|tab*)) >
<!ELEMENT intro (#PCDATA | p | h | br | b | i | u | tt | a | ul | ol | h3 | h4 | pre | sub | sup | table)* >
<!ELEMENT option (#PCDATA | p | h | br | b | i | u | tt | a | ul | ol | pre | sub | sup)* >
<!ATTLIST option name CDATA #REQUIRED>
<!ATTLIST option optional (true|false) "false">
<!ELEMENT tab (option+)>
<!ATTLIST tab name CDATA #REQUIRED>

<!ELEMENT p (#PCDATA | br | b | i | u | a | tt | ul | ol | sup | sub)* >
<!ELEMENT ul (li)+ >
<!ELEMENT ol (li)+ >
<!ELEMENT li (#PCDATA | br | b | i | u | a | tt)* >
<!ELEMENT h3 (#PCDATA) >
<!ELEMENT h4 (#PCDATA) >
<!ELEMENT h (#PCDATA) >
<!ELEMENT b (#PCDATA) >
<!ELEMENT i (#PCDATA) >
<!ELEMENT u (#PCDATA) >
<!ELEMENT a (#PCDATA) >
<!ELEMENT tt (#PCDATA) >
<!ELEMENT pre (#PCDATA) >
<!ELEMENT sup (#PCDATA) >
<!ELEMENT sub (#PCDATA) >
<!ELEMENT br EMPTY >
<!ATTLIST a href CDATA #REQUIRED>

<!ELEMENT table (tr)+ >
<!ELEMENT tr (th | td)+ >
<!ELEMENT td (#PCDATA) >
<!ELEMENT th (#PCDATA) >
<!ATTLIST td align CDATA #IMPLIED>
<!ATTLIST th align CDATA #IMPLIED>
<!ATTLIST td colspan CDATA #IMPLIED>
<!ATTLIST th colspan CDATA #IMPLIED>
<!ATTLIST td rowspan CDATA #IMPLIED>
<!ATTLIST th rowspan CDATA #IMPLIED>


<!ELEMENT ports (inPort*, outPort*) >
<!ELEMENT inPort (#PCDATA | br | b | i | u | tt | ul | ol)* >
<!ATTLIST inPort index CDATA #REQUIRED>
<!ATTLIST inPort name CDATA #REQUIRED>
<!ATTLIST inPort optional (true|false) "false">
<!ELEMENT outPort (#PCDATA | br | b | i | u | tt | ul | ol)* >
<!ATTLIST outPort index CDATA #REQUIRED>
<!ATTLIST outPort name CDATA #REQUIRED>

<!ELEMENT views (view+) >
<!ELEMENT view (#PCDATA | p | h | br | b| i | u | tt | a | ul | ol | pre | sub | sup)* >
<!ATTLIST view index CDATA #REQUIRED>
<!ATTLIST view name CDATA #REQUIRED>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/workflow/save/SaveWorkflowNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="save.png" type="Other">
    <name>Save Workflow</name>

    <shortDescription>
      Saves the workflow upon execution.   
    </shortDescription>

    <fullDescription>
        <intro>
            <p>
              Saves the workflow upon execution.
            </p>
        </intro>
    </fullDescription>

    <ports>
        <inPort index="0" name="Input">Ignored.</inPort>
        <outPort index="0" name="Output">Ignored.</outPort>
    </ports>
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/preproc/regexsplit/RegexSplitNodeFactory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd" >
<knimeNode icon="regexsplit.png" type="Manipulator">
	<name>Regex Split</name>
	<shortDescription>
		Splits an input string (column) into multiple groups according
		to a regular expression.
	</shortDescription>
	<fullDescription>
		<intro>
			<p>
				This node splits the string content of a selected column
				into logical groups using regular expressions. A group
				is identified by a pair of parentheses, whereby the
				pattern in such parentheses is a regular expression.
				Each content of each group is appended as an individual
				column.
			</p>

			<p>
				A short introduction to Groups and Capturing is given by
				in the
				<a
					href="http://java.sun.com/javase/6/docs/api/java/util/regex/Pattern.html#cg">
					Java API
				</a>
				. Some examples are given below:
			</p>
			<h4>Parsing Patent Numbers</h4>
			<p>
				Patent identifiers such as "US5443036-X21" consisting of
				a (at most) two letter country code ("US"), a patent
				number ("5443036") and possibly some application code
				("X21"), which is separated by a dash or a space
				character, can be grouped by the expression
				<tt>([A-Za-z]{1,2})([0-9]*)[ \-]*(.*$)</tt>.
				Each of the parenthesized terms corresponds to the
				aforementioned properties.
			</p>
			<h4>Strip File URLs</h4>
			<p>
				This is particularly useful when this node is used to
				parse the file URL of a file reader node (the URL is
				exposed as flow variable and then exported to a table
				using a Variable to Table node). The format of such
				URLs is similar to "file:c:\some\directory\foo.csv".
				Using the pattern
				<tt>[A-Za-z]*:(.*[/\\])(([^\.]*)\.(.*$))</tt>
				generates four groups (by counting the number of opening
				parentheses): The first group identifies the directory
				and is denoted by "(.*[/\\])". It consumes all characters
				until a final slash or backslash is encountered; in the example
				this refers to "c:\some\directory\". The second group
				represents the file name, whereby it encapsulates the
				third and fourth group. The third group (denoted by
				"([^\.]*)") consumes all characters after the directory,
				which are not a dot '.' (which is "foo" in the
				above example). The pattern expects a single dot
				(which is ignored) and finally the fourth group "(.*$)",
				which reads until the end of the string and indicates
				the file suffix ('csv'). The groups for the above
				example are
				<ol>
					<li>c:\some\directory</li>
					<li>foo.csv</li>
					<li>foo</li>
					<li>csv</li>
				</ol>
			</p>
		</intro>
		<option name="Ignore Case">
			Enables case-insensitive matching.
		</option>
		<option name="Multiline">
			Enables multiline mode, i.e. when selected the expression ^
			and $ match the start and end of the input string. This
			option only matters if the input string have line breaks.
		</option>
	</fullDescription>
	<ports>
		<inPort index="0" name="Data table">
			Input table with string column to be split.
		</inPort>
		<outPort index="0" name="Input with split columns">
			Input table amended by additional column representing the
			pattern groups.
		</outPort>
	</ports>
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/preproc/crossjoin/CrossJoinerNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="./xjoiner.png" type="Manipulator">
    <name>Cross Joiner</name>
    
    <shortDescription>
        Performs a cross join of two tables
    </shortDescription>
    
    <fullDescription>
        <intro>Performs a cross join of two tables. Each row of the top table is joined with 
        each row of the bottom table. Note, this is an extremely expensive operation as the number of rows in the
        output is the product of both input table row counts, by increasing the chunk size there will be a speed up. </intro>
        <option name="Bottom table's column suffix">
        The suffix attached to a column's name if the bottom table contains a column with the same name.
        The column names of the first inport are always retained. If there are duplicates found in the second table
        the suffix is added once or multiple times to ensure uniqueness. 
        </option>
        <option name="Separator for new RowIds"> This string will separate the rowids in the new data table. E.g. RowID1 + sep + RowID2</option>
        <option name="Chunk size: ">Number of rows read at once, increasing this
		      value yields faster execution time but also increases memory consumption.</option>
        <option name="Append top data tables RowIds"> If selected a new column will be attached to the output, containing the rowids of the top data table. </option>
        <option name="Column name(top): ">The name of the newly generated rowkey column.</option>
        <option name="Append bottom data tables RowIds ">If selected a new column will be attached to the output, containing the rowids of the bottom data table.</option>
        <option name="Column name(bottom): ">The name of the newly generated rowkey column.</option>
    </fullDescription>
    
    <ports>
        <inPort index="0" name="Top Table">The top table to be joined</inPort>
        <inPort index="1" name="Bottom Table">The bottom table to be joined</inPort>
        <outPort index="0" name="Joined Table">Cross join</outPort>
    </ports>    
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/preproc/filter/columnref/ColumnFilterRefNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="./refcolumnfilter.png" type="Manipulator">
	<name>Reference Column Filter</name>
	
	<shortDescription>
		The Reference Column Filter allows columns to be filtered from the first 
		table using the second table as reference.
	</shortDescription>
	
	<fullDescription>
		<intro>
			This node allows columns to be filtered from the first table using
			the second table as reference table. Depending on the dialog
			setting, either the columns from the reference table are included or
			excluded in the output table.
		</intro>
		
		<option name="In-/Exclude columns from reference table">
			Includes or excludes all columns from the reference table into the
			resulting table from the first input.
		</option>

        <option name="Ensure compatibility of column types">
            Ensures that the matching columns don't only have the same name but
            also the same type. Columns are only included or
            excluded if the column type of the first table is a super-type of
            the column type from the second table. If not selected, only the 
            column names need to match.
        </option>
		
	</fullDescription>
	
	<ports>
		<inPort index="0" name="Table to be filtered">
			Table from which columns are to be included or excluded
		</inPort>
		<inPort index="1" name="Reference table">
            Table with the columns used as references
        </inPort>
		<outPort index="0" name="Filtered table">
			Table with filtered columns
		</outPort>
	</ports>	
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/util/sampledata/SampleDataNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="./sampler.png" type="Source">
    <name>Data Generator</name>
    <shortDescription>Creates random data with clusters.</shortDescription>
    <fullDescription>
        <intro>
			Creates random data containing some clusters for Parallel Universes.
		    The data contains a certain fraction of noise patterns and data that
		    is generated to clusters (all clusters have the same size). The data is
		    normalized in [0, 1].
		</intro>
		<option name="Cluster Count">
			The number of clusters for each universe (comma separated).
		</option>
		<option name="Universe Sizes">
			The number of attributes for each universe (comma separated).
		</option>
		<option name="Pattern Count">
			Number of patterns (overall).
		</option>
		<option name="Standard Deviation">
			Std. dev. for each cluster.
		</option>
		<option name="Noise Fraction">
			Fraction of the overall data to be noise, i.e. randomly drawn data. 
			This value must be in [0, 1].
		</option>
		<option name="Random Seed">
			Seed for "deterministic" data generation.
		</option>
	</fullDescription>
    <ports>
		<outPort index="0" name="Random data with cluster ID">Contains the data with the cluster id as last column</outPort>
		<outPort index="1" name="Cluster centers">Contains the cluster centers. The attributes in the universes where
			the cluster is not located, are filled with missing values.</outPort>
	</ports>
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/viz/property/size/SizeAppenderNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode type="Visualizer" icon="./size_appender.png">
	<name>Size Appender</name>
	
	<shortDescription>
	    Appends sizes to one selected column.
	</shortDescription>
	
	<fullDescription>
		<intro>
		<p>
		Appends an existing size model (SizeHandler) to one selected column
		of the input table. 		
	    </p>
	    <p>
	    This may be useful if the column for which the size model is defined gets
	    lost somewhere in the workflow, is replaced by another column, or if there
	    are two different datasets with the same class column. 
	    </p>
		</intro>
	    <option name="Append sizes to: ">
		    Select the column to apply the size model to. It might be the same 
		    column, a different numeric column for which the size model should 
		    be reused, or a nominal column if the size model was defined for 
		    nominal values. Then the possible values must be exactly the same. 
	    </option>
	</fullDescription>
	
	<ports>
		<inPort index="0" name="Size model">Size model which size settings</inPort>
		<inPort index="1" name="Table">Table to which size settings should be applied to</inPort>
		<outPort index="0" name="Table with sizes">Input table with size information applied to one column</outPort>
	</ports>	
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/preproc/cellsplit/CellSplitterNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="./cellsplitter.png" type="Manipulator">
	<name>Cell Splitter</name>
	
	<shortDescription>
	    Splits the string representation of cells in one column of the table 
	    into separate columns or into one column containing a collection of 
	    cells, based on a specified delimiter.
	</shortDescription>
	
	<fullDescription>
		<intro>This node uses a user-specified delimiter character to
		split the content of a selected column into parts. It appends either a 
		fixed number of columns to the input table, each carrying one part of the 
		original column, or a single column containing a collection (list or 
		set) of cells with the split output. It can be specified whether the
		output consists of one or more columns, only one column containing 
		list cells, or only one column containing set cells in which duplicates
		are removed.<br />
		If the column contains more delimiters than needed 
		(leading to more parts than appended columns are available) the 
		additional delimiters are ignored (resulting in the last column containing
		the unsplit rest of the column).<br />
		If the selected column contains too
		few delimiters (leading to less parts than expected), empty columns
		will be created in that row.<br />
		Based on the delimiters and the resulting parts the collection cells
		can have different sizes.
		The content of the new columns will be trimmed if specified 
		(i.e. leading and trailing spaces will be deleted).
		</intro>
		<option name="Column selection"> 
			Select the column whose values are split.
		</option>
		<option name="Delimiter">Specify the delimiter in the value, that 
		splits each part.
		</option>
        <option name="Use escape character">If enabled, the backslash ("\")
        can be used to escape characters, such as "\t" for tabs. You can use
        the full escape capabilities of Java.
        </option>
	    <option name="Quotation character">Specify the quotation character, if 
	    the different parts in the value are quoted. (The character to escape
	    quotes is always the backslash.) If no quotation character
	    is needed leave it empty.
		</option>
        <option name="remove leading and trailing white space chars (trim)">
        If checked, leading and trailing white spaces of each part (token) will 
        be deleted.
        </option>		
        <option name="Output - as list">
        If selected, the output will consist of one column containing list
        collection cells in which the split parts are stored. Duplicates
        can occur in list cells.
        </option>
        <option name="Output - as set (remove duplicates)">
        If selected, the output will consist of one column containing set
        collection cells in which the split parts are stored. Duplicates
        are removed and can not occur in set cells.
        </option>
        <option name="Output - as new columns">
        If selected, the output will consist of one or more columns, each 
        containing a split part.
        </option>
		<option name="Set Array Size">Check this and specify the number of columns
		to append. All created columns will be of type String. (See above for 
		what happens if the split produces a different number of parts.)
		</option>
		<option name="Guess Size and Column Types">If this is checked, the node
		performs an additional scan through the entire data table and computes 
		the number of columns needed to hold all parts of the split. In addition
		it determines the column type of the new columns. 
		</option>
		<option name="Missing Value Handling">If select, the node creates 
		empty string cell instead of missing value cells. 
        </option>
	</fullDescription>
	
	<ports>
		<inPort index="0" name="Input Table">Input data table with column containing the cells to split</inPort>
		<outPort index="0" name="Output Table">Output data table with additional columns.</outPort>
	</ports>	
</knimeNode>

=== oct15demo/browserUI/org.knime.base/src/org/knime/base/node/mine/regression/polynomial/learner2/PolyRegLearnerNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="polyRegLearner.png" type="Learner">
    <name>Polynomial Regression Learner</name>

    <shortDescription>Learner that builds a polynomial regression model from the input data</shortDescription>

    <fullDescription>
        <intro>
            This node performs polynomial regression on the input data and computes the coefficients that minimize the
            squared error. The user must choose one column as target (dependent variable) and a number of independent variables. By
            default, polynomials with degree 2 are computed, which can be changed in the dialog.
            <br />
            If the optional PMML inport is connected and contains 
    		preprocessing operations in the TransformationDictionary those are 
    		added to the learned model.
        </intro>
        <tab name="Regression settings">
            <option name="Target column">The column that contains the dependent "target" variable.</option>
            <option name="Polynomial degree">The maximum degree the polynomial regression function should have.</option>
            <option name="Column Selection">Select the columns containing the independent variables and
                move them to the "include" list. </option>                
        </tab>
        <tab name="View settings">
            <option name="Number of data points to show in view">
                This option can be use to change the number of data points in
                the node view if e.g. there are too many points. The default
                value is 10,000 points.            
            </option>
        </tab>
    </fullDescription>

    <ports>
        <inPort name="Training data" index="0">
            The input samples, which of the columns are used as independent variables can be configured in the dialog.
             The input must not contain missing values, you have to fix them by e.g. using the Missing Values node.
        </inPort>
        <inPort index="1" name="PMML Preprocessing">Optional PMML port object containing preprocessing operations.</inPort>
        <outPort name="Regression model" index="0">
            The computed regression coefficients as a PMML model for use in the Regression Predictor.
        </outPort>
        <outPort name="Data with training error" index="1">
            Training data classified with the learned model and the corresponding errors.
        </outPort>
        <outPort name="Coefficients and Statistics" index="2">
            The computed regression coefficients as a table with statistics related to the training data.
        </outPort>
    </ports>

    <views>
        <view index="0" name="Learned Coefficients">Shows all learned coefficients all attributes.</view>
        <view index="1" name="Scatter Plot">
            Shows the data points and the regression function in one dimension.
        </view>
    </views>
</knimeNode>
